### ISSUE TITLE
I can't install the package, how can I solve this?

### ISSUE THREAD

**Issue by MonicaCalSan** [rformassspectrometry/MsBackendHmdb#3]
I'm trying to install the package, but I get this message:
Warning messages:
1: In .inet_warning(msg) :
  package ‘MsBackendHmdb’ is not available for Bioconductor version '3.12'

A version of this package for your version of R might be available elsewhere, see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

Is there something I can do for using it? I would like not to change my actual R version, since I'm in the middle of the development of some code, but I would like to use this package to implement some improvements for my code.

**Comment by jorainer** [comment]
The `MsBackendHmdb` is not (yet) in Bioconductor. To install it you need to call `BiocManager::install("RforMassSpectrometry/MsBackendHmdb")`.

**Comment by MonicaCalSan** [comment]
Thanks!!!
