### ISSUE TITLE
Why precursorMz is always NA?

### ISSUE THREAD

**Issue by MonicaCalSan** [rformassspectrometry/MsBackendHmdb#4]
I think this is probably something related to the way HMDB configure its spectrum data, and thus something without a solution, but I would need this info to implement this package inside my code. Is it possible to have the precursorMz info or at least monoisotopic neutral mass?

**Comment by jorainer** [comment]
unfortunately HMDB does not provide the precursor m/z (or at least I could not find it in the xml files) - also the monoisotopic mass is not recorded in the xml files. That one you could eventually get from the "compound" annotations of HMDB (using the compound/HMDB ID of the metabolite)?

**Comment by MonicaCalSan** [comment]
This was my impression, I was also looking at the xml file and didn't find this info. Yes, I can get it from the annotation, but I first need to filter the dataset to retain only spectra that can fit mine. Thanks for answering, I think I'm going to try Massbank!
